datasource:
  type: "json"

language: "en"

web-editor:
  enable: true
  port: 4567
  https:
    enable: false
    keystore-file-path: ""
    keystore-password: ""
  trustIp: []

account:
  username: ""
  password: ""
