sendMessageDelay: 4
welcome_message:
  - §bWelcome to Server，§e%player_name%§b!
  - §bPlease be nice to others and have fun!
op_join: §c[Administrator] §e%player_name% §cis now online
op_quit: §c[Administrator] §e%player_name% §cis now offline
player_join: §c[Player] §e%player_name% §cis now online
player_quit: §c[Player] §e%player_name% §cis now offline
